app_home:
    path: /home
    controller: App\Controller\HomeController::index
animal_new:
    path: /animals/new
    controller: App\Controller\AnimalController::new
remove_animal:
    path: /animals/remove/{id}
    controller: App\Controller\AnimalsController::delete
app_demande:
    path: '/demande/{animalId}'
    controller: App\Controller\DemandeController::demande
edit_demande:
    path: '/demandes/{id}/edit'
    controller: App\Controller\DemandeController::edit
demande:
    path: '/demandes/{userId}'
    controller: 'App\Controller\DemandeController::showDemandes'

