# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    upload_directory: '%kernel.project_dir%/public/uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    App\Security\EmailVerifier:
        class: App\Security\EmailVerifier # Adjust the class if needed
        arguments:
            - '@translator.default' # Assuming you have a translator service
            - '#framework.mailer' # Replace with your mailer service name

    App\Security\CustonAuthSucessHandler:
        arguments:
            - '@router'
            - '@security.authorization_checker'


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    asset_mapper.public_assets_path_resolver:
        class: Symfony\WebpackEncoreBundle\Asset\PublicPathResolver
        arguments:
            - '%env(ASSETS_URL)%'

    App\Security\RedirectAdminAccessListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    App\DefaultPasswordRedirectSubscriber:
        tags:
            - { name: kernel.event_subscriber }


